### ISSUE TITLE
Not changed whole theme of Xcode

### ISSUE THREAD

**Issue by khushDesai** [Rep0se/xcode-themes#2]
I have added this themes but its look like this:

![screen shot 2018-05-22 at 5 22 58 pm](https://user-images.githubusercontent.com/29880773/40360768-cd41d4d6-5de4-11e8-9e97-3796984375e4.png)

I want Whole xcode theme in dark color like this: 
![screen shot 2018-05-22 at 5 23 24 pm](https://user-images.githubusercontent.com/29880773/40360816-eb27393c-5de4-11e8-95e6-3806f70eb642.png)

**Comment by Rep0se** [comment]
"Invert Colors" (in System Preferences -> Accessibility -> Display -> Invert Colors OR setting up a "Ctrl-Opt-Cmd-8" shortcut in System Preferences -> Keyboard -> Shortcuts -> Accessibility -> Invert Colors)
